# Part of the Carbon Language project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Setup build environment (Ubuntu)
runs:
  using: composite
  steps:
    # Ubuntu images start with ~23GB available; this takes a few seconds to add
    # ~22GB more.
    #
    # Although we could delete more, if we run into a limit, not deleting
    # everything provides a little flexibility to get space while trying
    # to shrink the build.
    - name: Free up disk space
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      with:
        android: true
        dotnet: true
        haskell: true
        # Enabling large-packages adds ~3 minutes to save ~4GB, so turn it off
        # to save time.
        large-packages: false

    - name: Show system LLVM and Clang installation
      shell: bash
      run: |
        dpkg -l '*clang*' '*llvm*'

    # Install a recent version of LLVM. We use LLVM's apt.llvm.org in order to
    # have access to all released versions, instead of the GitHub releases which
    # are often missing binaries for ubuntu x64.
    - name: Download LLVM and Clang installation
      env:
        clang_version: 19
      shell: bash
      run: |
        echo '*** Installing upstream clang packages'
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${clang_version} all

        echo "/lib/llvm-19/bin" >> "$GITHUB_PATH"
