# Part of the Carbon Language project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# TODO: Uncomment when macos can find cstdio.
# load("//bazel/carbon_rules:defs.bzl", "carbon_binary")

# TODO: Uncomment when macos can find cstdio.
# carbon_binary(
#     name = "hello_world",
#     srcs = ["hello_world.carbon"],
# )
